import { Metadata } from "next"
// import { ErrorWrapper } from "./error-wrapper"

export const metadata : Metadata = {
  title: {
    default: " Next.js App Layout",
    template: "%s | Manavi",

  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>

        <header 
        style={{
          backgroundColor: "lightblue",
          padding: '10px',
        }}>
          <p>Header</p>
        </header>

   {children}

        <footer
        style={{
          backgroundColor: '#f0f0f0',
          padding: '10px',
        }}>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  )
}
