export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
  }
  
  export default function MarketingLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <html lang="en">
        <body>
  
          <header 
          style={{
            backgroundColor: "lightblue",
            padding: '10px',
          }}>
            <p>Header</p>
          </header>
  
          {children}
  
          <footer
          style={{
            backgroundColor: '#f0f0f0',
            padding: '10px',
          }}>
            <p>Footer</p>
          </footer>
        </body>
      </html>
    )
  }
  